name: Validation
on: [pull_request]

jobs:
  govalidations:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.23
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Config
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1
    - name: Run golint and unit tests
      run: |
        golangci-lint run -c ./.golangci.yaml --fast
        go test -race --cover ./...